# Generated by Django 2.0.6 on 2018-06-26 05:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('service', models.CharField(choices=[('AM Break', 'AM_BREAK'), ('Breakfast', 'BREAKFAST'), ('Lunch', 'LUNCH'), ('PM Break', 'PM_BREAK'), ('Dinner', 'DINNER')], default='AM Break', max_length=20)),
                ('quantity', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('status_choices', models.CharField(choices=[('Ready', 'READY'), ('Stand-by', 'STANDBY'), ('Enroute', 'ENROUTE'), ('Delivered', 'DELIVERED')], default='Stand-by', max_length=20)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(default=None, on_delete=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
