# Generated by Django 2.0.6 on 2018-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_service_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.CharField(choices=[('10:00 a.m.', '10:00 a.m.'), ('11:00 a.m.', '11:00 a.m.'), ('10:00 p.m.', '10:00 p.m.'), ('11:00 p.m.', '11:00 p.m.')], default='10:00 a.m.', max_length=20),
        ),
    ]
