# Generated by Django 2.0.6 on 2018-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180629_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(choices=[('10:00', '10:00 a.m.'), ('11:00', '11:00 a.m.'), ('15:00', '3:00 p.m.'), ('18:00', '6:00 p.m.')], default='10:00 a.m.'),
        ),
    ]
