# Generated by Django 2.0.6 on 2018-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180629_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.CharField(choices=[('0', '10:00 a.m.'), ('1', '11:00 a.m.'), ('2', '3:00 p.m.'), ('3', '6:00 p.m.')], default='10:00 a.m.', max_length=200),
        ),
    ]
