# Generated by Django 2.0.6 on 2018-07-08 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180708_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
