# Generated by Django 2.0.6 on 2018-07-08 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180708_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 11, 28, 15, 829218, tzinfo=utc)),
        ),
    ]
