# Generated by Django 2.0.7 on 2018-07-09 20:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_auto_20180708_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=1000)),
                ('updated', models.DateTimeField(default=datetime.datetime(2018, 7, 9, 20, 45, 40, 971145, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('AM Break', 'AM_BREAK'), ('Breakfast', 'BREAKFAST'), ('Lunch', 'LUNCH'), ('PM Break', 'PM_BREAK'), ('Dinner', 'DINNER'), ('Popup', 'POPUP')], default='AM Break', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 20, 45, 40, 969758, tzinfo=utc)),
        ),
    ]
